import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const DATA_DIR = path.join(ROOT, 'data');
export const SOURCES_DIR = path.join(DATA_DIR, 'sources');
export const JOBS_DIR = path.join(DATA_DIR, 'jobs');
export const CACHE_DIR = path.join(DATA_DIR, 'cache');
export const TMP_DIR = path.join(DATA_DIR, 'tmp');
export const BROWSER_PROFILE_DIR = path.join(DATA_DIR, 'browser-profile');
export const PLAYWRIGHT_BROWSERS_DIR = path.join(ROOT, '.playwright-browsers');
export const CONFIG_DIR = path.join(ROOT, 'config');
export const LOCAL_CONFIG = path.join(CONFIG_DIR, 'local.json');

export const NTNU_VPN_PREFIXES = [
  '140.122.57.',
  '140.122.56.',
  '140.122.20.',
  '140.122.21.',
];

export const STATUS = Object.freeze({
  READY_OA: '已取得_OA',
  READY_VPN: '已取得_VPN',
  READY_OTHER: '已取得_來源未判定OA',
  PAYWALL: '付費牆',
  LOGIN_REQUIRED: '需要登入',
  CAPTCHA: 'CAPTCHA',
  NO_PDF: '找不到PDF',
  MATCH_REVIEW: 'DOI配對待確認',
  UNRESOLVED: 'Reference無法解析',
  INVALID_PDF: '內容不是PDF',
  DOWNLOAD_FAILED: '下載失敗',
  API_MISSING: '缺少API憑證',
  API_PERMISSION_REQUIRED: '需要API全文權限',
  PUBLISHER_BLOCKED: '出版商拒絕自動存取',
  NON_ARTICLE: '非論文參考資料',
  OA_DOWNLOAD_FAILED: '已知OA但自動下載失敗',
  PREVIEW_ONLY: '僅取得預覽_非全文',
  PENDING: '等待處理',
});

export const SI_STATUS = Object.freeze({
  NOT_REQUESTED: '未要求',
  PENDING: '等待蒐集SI',
  COLLECTED: '已取得SI',
  NOT_FOUND: '未發現SI',
  DOWNLOAD_FAILED: 'SI下載失敗',
  MANUAL_REQUIRED: 'SI需瀏覽器處理',
  DISCOVERY_BLOCKED: 'SI確認受出版商阻擋',
  NO_DOI: 'DOI待確認_未找SI',
});

export const SUCCESS_STATUSES = new Set([STATUS.READY_OA, STATUS.READY_VPN, STATUS.READY_OTHER]);
export const RETRYABLE_STATUSES = new Set([
  STATUS.PAYWALL,
  STATUS.LOGIN_REQUIRED,
  STATUS.CAPTCHA,
  STATUS.NO_PDF,
  STATUS.INVALID_PDF,
  STATUS.DOWNLOAD_FAILED,
  STATUS.UNRESOLVED,
  STATUS.API_MISSING,
  STATUS.API_PERMISSION_REQUIRED,
  STATUS.PUBLISHER_BLOCKED,
  STATUS.OA_DOWNLOAD_FAILED,
  STATUS.PREVIEW_ONLY,
  STATUS.PENDING,
]);

export const FAILURE_CODE = Object.freeze({
  PREVIEW_ONLY: 'PREVIEW_ONLY',
  INCOMPLETE_DOCUMENT: 'INCOMPLETE_DOCUMENT',
  IDENTITY_MISMATCH: 'IDENTITY_MISMATCH',
  IDENTITY_UNVERIFIED: 'IDENTITY_UNVERIFIED',
  VERSION_UNVERIFIED: 'VERSION_UNVERIFIED',
  PREPRINT_NOT_ALLOWED: 'PREPRINT_NOT_ALLOWED',
  API_CREDENTIAL_INVALID: 'API_CREDENTIAL_INVALID',
  API_FEATURE_NOT_ENABLED: 'API_FEATURE_NOT_ENABLED',
  INSTITUTION_ENTITLEMENT_FALSE: 'INSTITUTION_ENTITLEMENT_FALSE',
  AUTH_NETWORK_MISMATCH: 'AUTH_NETWORK_MISMATCH',
  FORMAT_NOT_PERMITTED: 'FORMAT_NOT_PERMITTED',
  QUOTA_THROTTLED: 'QUOTA_THROTTLED',
  OA_LOCATION_STALE: 'OA_LOCATION_STALE',
  REPOSITORY_METADATA_ONLY: 'REPOSITORY_METADATA_ONLY',
  PUBLISHER_AUTOMATION_BLOCKED: 'PUBLISHER_AUTOMATION_BLOCKED',
  DOWNLOAD_FAILED: 'DOWNLOAD_FAILED',
  NO_CANDIDATE: 'NO_CANDIDATE',
});

export const RETRYABLE_SI_STATUSES = new Set([
  SI_STATUS.PENDING,
  SI_STATUS.DOWNLOAD_FAILED,
  SI_STATUS.MANUAL_REQUIRED,
  SI_STATUS.DISCOVERY_BLOCKED,
]);
